export const CONSTANTS = {
    API_URL: 'http://127.0.0.1:8000/api',
    FILES_FOLDER: 'backup/',
    MAX_USERNAME_LENGTH: 20,
    MIN_USERNAME_LENGTH: 3,
    MIN_PASSWORD_LENGTH: 8,
    DEFAULT_CURRENT_PAGE: 1,
    DEFAULT_PAGE_SIZE: 10,
    DEFAULT_TOAST_DURATION: 3000,
};
